
services:
  postgres:
    image: postgres:16
    container_name: postgres-prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis-prod
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-prod
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"

  auth-service:
    image: yanghyunwoo/mockio-auth-service:latest
    container_name: auth-service-prod
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${AUTH_DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      INTERNAL_AUTH_TOKEN: ${INTERNAL_TOKEN}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}


      REDIS_HOST: redis
      REDIS_PORT: 6379

      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started

  core-service:
    image: yanghyunwoo/mockio-core-service:latest
    container_name: core-service-prod
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${CORE_DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      OPEN_AI_KEY: ${OPENAI_API_KEY}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      INTERNAL_CORE_TOKEN: ${INTERNAL_TOKEN}
      RECAPTCHA_SECRET: ${RECAPTCHA_SECRET}
      REDIS_HOST: redis
      REDIS_PORT: 6379

      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started

  support-service:
    image: yanghyunwoo/mockio-support-service:latest
    container_name: support-service-prod
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${SUPPORT_DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      INTERNAL_SUPPORT_TOKEN: ${INTERNAL_TOKEN}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDFLARE_R2_ACCESS_KEY: ${CLOUDFLARE_R2_ACCESS_KEY}
      CLOUDFLARE_R2_SECRET_KEY: ${CLOUDFLARE_R2_SECRET_KEY}
      CLOUDFLARE_R2_ACCOUNT_ID: ${CLOUDFLARE_R2_ACCOUNT_ID}
      CLOUDFLARE_R2_BUCKET_NAME: ${CLOUDFLARE_R2_BUCKET_NAME}
      CLOUDFLARE_R2_ENDPOINT: ${CLOUDFLARE_R2_ENDPOINT}
      REDIS_HOST: redis
      REDIS_PORT: 6379

      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started

  gateway:
    image: yanghyunwoo/mockio-gateway:latest
    container_name: gateway-prod
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - auth-service
      - core-service
      - support-service

  frontend:
    image: mockio-front:latest
    container_name: mockio-front-prod
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: https://mockio.cloud:8080/api
      API_URL: http://gateway:8080/api
    depends_on:
      - gateway

  ollama:
    image: ollama/ollama
    container_name: ollama-prod
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always

volumes:
  ollama: