spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/v1/**
        - id: core-service
          uri: http://core-service:8080
          predicates:
            - Path=/api/users/v1/**,/api/interview/v1/**,/api/feedback/v1/**
        - id: support-service
          uri: http://support-service:8080
          predicates:
            - Path=/api/notice/v1/**,/api/faq/v1/**,/api/notification/v1/**,/api/file/v1/**,/api/questionboard/v1/**,/api/comment/v1/**

  #          filters: 앞의 segment 하나 제거
#            - StripPrefix=1
#            - id: group-service
#              uri: http://localhost:8083
#              predicates:
#                - Path=/api/groups/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8080/api/auth/v1/.well-known/jwks.json

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    tags:
      application: ${spring.application.name}