server:
  port: 8080

services:
  core:
    base-url: http://core-service:8080
    connect-timeout-ms: 2000
    read-timeout-ms: 3000

internal:
  support:
    token: ${INTERNAL_SUPPORT_TOKEN}

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off

spring:
  messages:
    basename: messages/apiResponseMessage
    encoding: UTF-8
  application:
    name: support-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  config:
    import: optional:classpath:application-kafka.yaml
  kafka:
    consumer:
      group-id: support-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8080/api/auth/v1/.well-known/jwks.json

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

cloudflare:
  r2:
    access-key: ${CLOUDFLARE_R2_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_R2_SECRET_KEY}
    account-id: ${CLOUDFLARE_R2_ACCOUNT_ID}
    bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME}
    region: auto
    endpoint: ${CLOUDFLARE_R2_ENDPOINT}
